apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: postgres-service
    app: sigip

spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: sigip
