apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db-deploy
  labels:
    name: postgres-db
    app: sigip
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: sigip
  template:
    metadata:
      name: postgres
      labels:
        name: postgres-pod
        app: sigip
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432
