apiVersion: v1
kind: Service
metadata:
  name: todo-client-service
  labels:
    name: client-service
    app: todo
    
spec:
  type: NodePort
  ports:
    - port: 85
      targetPort: 80
      nodePort: 30001
  selector:
    name: todo-client-pod
    app: todo
