apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  labels:
    name: api-service
    app: todo
    
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3003
  selector:
    name: todo-api-pod
    app: todo
